development:
  sessions:
    default:
      database: giga_development
      hosts:
        - localhost:28017
      options:
        consistency: :strong
  options:
test:
  sessions:
    default:
      database: giga_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong
production:
  sessions:
    default:
      uri: "mongodb://njerichelimo:ingokho1@hatch.mongohq.com:10034/app003132345"
      options:
      skip_version_check: true
      safe: true
